---
- name: Ensure redash base directory exists
  ansible.builtin.file:
    path: "{{ redash_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Ensure postgres data directory exists
  ansible.builtin.file:
    path: "{{ redash_postgres_data_dir }}"
    state: directory
    owner: "70"   # postgres uid in alpine image
    group: "70"
    mode: "0700"
